//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeDrinkersEntities : DbContext
    {
        public CoffeeDrinkersEntities()
            : base("name=CoffeeDrinkersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoffeeAdditions> CoffeeAdditions { get; set; }
        public virtual DbSet<CoffeeDrinkersUsers> CoffeeDrinkersUsers { get; set; }
        public virtual DbSet<Coffees> Coffees { get; set; }
        public virtual DbSet<CoffeeTypes> CoffeeTypes { get; set; }
    }
}
