//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coffees()
        {
            this.CoffeeDrinkersUsers = new HashSet<CoffeeDrinkersUsers>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Sugar { get; set; }
        public Nullable<int> CoffeeTypeID { get; set; }
        public Nullable<int> AdditionsID { get; set; }
    
        public virtual CoffeeAdditions CoffeeAdditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoffeeDrinkersUsers> CoffeeDrinkersUsers { get; set; }
        public virtual CoffeeTypes CoffeeTypes { get; set; }
    }
}
